### ISSUE TITLE
[FEATURE REQUEST] Add multiple HTML entry point for parcel plugin

### ISSUE THREAD

**Issue by bogdan-nourescu** [101arrowz/pwa-manifest#11]
## The problem
What can't you do right now that you want added as a new feature?
I need to change multiple html files, not just index.html after i generate all the icons.
My apps usually consists of multiple single page apps (login.html, index.html, admin.html)

## Possible solution
If you have any idea for a possible solution, please write it here.
You can change this [line](https://github.com/101arrowz/pwa-manifest/blob/f522192d5d62386da132698c7d0d97e664bdab09/packages/parcel-plugin-pwa-manifest/index.ts#L74):
`const injectInto = [resolve(outDir, 'index.html')];`
with something like:
`const injectInto = (opts.entryPoints || ['index.html]).map( (file)=> resolve(outDir, file) );`

**Comment by 101arrowz** [comment]
I was putting this off, but I'll definitely see what I can do.

**Comment by 101arrowz** [comment]
So, I've released `v3` and with it automatic injection into all HTML files in the build. Unfortunately now you can't disable any of them. I'll add an option for disabling certain HTML files soon, I just have to work out a few annoying bits and it should work fine.

**Comment by bogdan-nourescu** [comment]
I, for one, i would have prefered to have an option to specify the files where you want it. The reason is that i dont give parcel all the html files as entrypoints, cause it fails to build a good dependency tree out of it. So i run a for loop and run the build separate. Until now, i was only using this plugin on first build, but i can make it run on all the builds, even tho it will build the same icons over and over again.

    for (let i = 0; i < project.build.length; i++) {
        console.log("Building " + project.build[i] + "\n\n\n\n");
        const bundler = new Bundler(project.build[i], options);
        if (i === 0) {
            pwaManifest(bundler);
        }
        await parcelPluginText(bundler);
        await bundler.bundle();
        if (i === 0) {
            await waitEvent(bundler, "pwaBuildEnd");
        }
    }

**Comment by 101arrowz** [comment]
I see. Could you elaborate on what you mean by it making a "bad dependency tree"? I'll certainly add in the manual option parameter in a day or two, but I'd like to understand the reason for bundling multiple times. Doing it just usually saves a lot of time.

By the way, if you use v3, you don't need to wait for `pwaBuildEnd` anymore. The bundler waits for the manifest generation to complete.

**Comment by bogdan-nourescu** [comment]
I have some dependencies that i use both in index.html and admin.html. For some reason it includes than twice in my app. Most of my dependencies just create HTML tags with `customElements.define` and that function fails if you try to include the same tag twice. 
I haven't tried it recently, but at some point, i was just try catch-ing all customElements.define.
I also noticed that it was including dependencies that wore not part of the dependency tree of index.html.

My dirty fix, was to build then separately and it worked for me.

**Comment by 101arrowz** [comment]
I don't know what custom logic you have, but have you tried simply running `parcel build index.html admin.html` from the command line just to see if the code is still duplicated? The entire point of a bundler over a minifier is to efficiently package dependencies, and I've never seen duplicated code in my Parcel builds, so I'm quite confused that you're experiencing that.

Try using [`parcel-plugin-bundle-visualizer`](https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser) once or twice just to see your dependency tree in full if it still doesn't work after running the CLI.

**Comment by bogdan-nourescu** [comment]
I was just playing around with that plugin now.
I will test and see if it was a mistake i did, or if it does have a bug in the dependency tree it generates for my app.
I tested V3 and it seem to be a lot faster that before. Thank you.

**Comment by bogdan-nourescu** [comment]
Yes, it generates a bad dependency graph for my app,
Its mostly because i reuse a lot of elements in different parts of my app.
A simple example is:
in admin.html i have lazy loaded B, C, D, E
dep B, C, D, E all depend on A.
Since A is not lazy loaded, Dependency A is moved to admin.html as a dependency.

Same thing happens between index.html and admin.html. Some dependency gets moved to Admin.html, so when i load in index.html that dependency, i actually load admin.html that has a lot more stuff than i need, including some duplicate dependencies.

My options are:

- Lazy load a lot more things, but it might make my code a lot harder to understand.
- Make my dependencies so that if i import them multiple times, it's ok and add more lazy-load things that don't get included correctly in the bundles.
- Build the html files separately, cause it seemed to work.

**Comment by 101arrowz** [comment]
Interesting. I'd suggest you file a bug report so that can get fixed in Parcel v2. I usually don't lazy load so I don't have those issues.

And yes, the build times have been drastically decreased in v3. Now they start at the beginning of the build rather than the end, so it's parallel with the build itself.

**Comment by 101arrowz** [comment]
Also, for now try following the new [documentation for `@pwa-manifest/core`](https://github.com/101arrowz/pwa-manifest/tree/master/packages/core/README.md), which should give instructions on how to do what you need very efficiently.

**Comment by bogdan-nourescu** [comment]
It works perfectly.
There is a typo in the sample code in the docs... You generate the meta tag with `manifest.webmanifest`, and the sample code has `manifest.json`

**Comment by 101arrowz** [comment]
Great! I'm probably going to close this issue seeing as for people with advanced use cases that involve not bundling all HTML files at once, they can use the core generator.

I'm well aware that I used `manifest.json`, it's a much more popular (albeit not spec-compliant) way of denoting a web manifest.
