### ISSUE TITLE
[BUG] Impossible to set apple touch icon padding to 0.

### ISSUE THREAD

**Issue by akoppela** [101arrowz/pwa-manifest#13]
## Describe the bug
It's not possible to set apple touch icon padding to 0.

## Expected behavior
It should be possible to set apple touch icon padding to 0.

## Actual behavior
The script uses `|| 12` as default value. 0 being falsy in JS always falls back to 12. BTW why default value is 12?

## To reproduce
Set apple touch icon padding to 0.

**Comment by 101arrowz** [comment]
That's a pretty stupid mistake on my part, thanks for pointing it out! Will fix in a new update.

**Comment by akoppela** [comment]
Thank you very much for quick fix.
