### ISSUE TITLE
Parcel 2 support

### ISSUE THREAD

**Issue by vincelwt** [101arrowz/pwa-manifest#15]
Hi,
It would be awesome to be able to use this module with the new parcel.
Thanks a lot for your work

**Comment by vincelwt** [comment]
Just saw your comment on https://github.com/101arrowz/pwa-manifest/issues/10#issuecomment-607673332, so I'll close it in the meantime.

**Comment by 101arrowz** [comment]
Thanks for the reminder! I'm going to try to release the Parcel v2 version of the plugin pretty soon (i.e. once I figure out how to inject custom HTML in).

**Comment by 101arrowz** [comment]
@vincelwt, the [Parcel 2 plugin](https://npmjs.com/package/parcel-config-pwa-manifest) has been released.
