### ISSUE TITLE
[RFC] Test Parcel 2 Support

### ISSUE THREAD

**Issue by 101arrowz** [101arrowz/pwa-manifest#16]
The Parcel 2 version of the plugin has been released. Given that it's one of the first functional community plugins written for Parcel 2, preliminary bug reports would be very helpful! Please reply with any comments.

**Comment by jekor** [comment]
I'm using parcel-config-pwa-manifest 0.0.8 and have not used previous versions. I get an error about the `magick` format.

Command: `parcel build --no-cache index.html`

```
Error: Manifest creation failed: An unknown error ocurred during the Apple Touch Icon creation process: Error: Unsupported output format magick
    at Object.<anonymous> (/nix/store/b3z9ri2vnm6wb4qz9114w07agblh1hcy-test-0.1.0/node_modules/parcel-transformer-pwa-manifest/lib/index.js:92:23)
    at Generator.throw (<anonymous>)
    at rejected (/nix/store/b3z9ri2vnm6wb4qz9114w07agblh1hcy-test-0.1.0/node_modules/parcel-transformer-pwa-manifest/lib/index.js:6:65)
```

`.parcelrc`
```
{
  "extends": ["@parcel/config-default", "parcel-config-pwa-manifest"]
}
```

`package.json`
```
{
  "pwaManifest": {
    "name": "test",
    "genIconOpts": {
      "baseIcon": "favicon.svg"
    }
  }
}
```

`index.html`
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test</title>
</head>
<body>
</body>
</html>
```

`favicon.svg` exists and is a valid SVG.

If I run the generator manually it seems to work correctly, but I receive the error under parcel. Apart from the error, it would be nice to have an option to disable generating the Apple Touch Icon.

**Comment by 101arrowz** [comment]
[These lines](https://github.com/101arrowz/pwa-manifest/blob/master/packages/core/index.ts#L726-L740) alone may have caused the issue. I believe that the issue is with `sharp` and/or vips, but I'll look into this further. Could you try installing ImageMagick to see if that fixes things?

**Comment by jekor** [comment]
From the ldd output of `node_modules/sharp/build/Release/sharp.node` ImageMagick is linked. I don't know if the imagemagick program is available at runtime (although it should be).

The other icons seem to generate without errors. I wonder what's different about the Apple Touch Icon.

**Comment by jekor** [comment]
I found the problem. I'm using Nix, and the Nix vips package is compiled without librsvg. Once I added that, Apple Touch Icon generation worked. I'll open a PR with the Nix package maintainers.
