### ISSUE TITLE
[FEATURE REQUEST] base paths

### ISSUE THREAD

**Issue by adrian2x** [101arrowz/pwa-manifest#20]
## The problem
Is it possible to specify the serving path for icons?

## Possible solution
ie. the plugin will generate srcs like `/icon-180x180.hash.png` but I want to make it load from `/static/icon-180x180.hash.png`.

is this supported?

**Comment by 101arrowz** [comment]
The base path is automatically detected from the public URL passed to Parcel for `parcel-plugin-pwa-manifest`. See [the Parcel docs](https://parceljs.org/cli.html#set-the-public-url-to-serve-on). The detection for `parcel-config-pwa-manifest` is rather rudimentary. In any case, at the moment the plugin does not support prepending a path specifically to the icon files. I can add this feature in, but I'd like to know why you want a `/static/` prefix to gather more use-case info. @adrian2x

**Comment by adrian2x** [comment]
@101arrowz thanks for the clarification. I was not configuring my targets with an explicit `publicUrl` but passing it as a cli argument. After adding a section like this, I got the paths right:
```
    "targets": {
      "main": {
        "distDir": "./dist",
        "publicUrl": "/dist/"
      }
    },
```
