### ISSUE TITLE
[BUG] Parcel v2 public-url option is ignored

### ISSUE THREAD

**Issue by s-weigand** [101arrowz/pwa-manifest#34]
## Describe the bug
First of all, thank you for the nice plugin ❤️ 

When using parcel2 with the `--public-url` option its is ignored for the `<meta>` and `<link>` tags as well as in the manifest.

## Expected behavior
I would expect that `public-url` is prefixed as it is done for the other assets parcel processes.

## Actual behavior
All links start with `/`, which breaks the PWA when used in a subdirectory of a domain as is the case with github pages.

## To reproduce
```console
$ parcel build src/index.html --public-url https://some-domain.com
```

## Additional context
To fix the issues I ended up with a [post-processing python script](https://github.com/s-weigand/dev-emoji-page/blob/main/utils/post_build.py) to prefix all links.

**Comment by 101arrowz** [comment]
Will be fixed in the next release along with #40, thanks for the report.
