### ISSUE TITLE
[BUG] Parcel v2 bundeled index.html renamed to parent folder name if baseIcon is png

### ISSUE THREAD

**Issue by s-weigand** [101arrowz/pwa-manifest#35]
## Describe the bug
Since the created icons have many artifacts when created from `svg` I use a 512x512 `png` as `baseIcon`, this leads to `index.html` and all css and js bundels to be renamed to the parent folders name. So I have to add an extra step after bundeling  to rename the file back to `index.html`. The strange this is that this only happens with the name `index.html`, e.g. `index2.html` gets bundled to `index2.html`

## Expected behavior
The bunded `index.html` persists in its name.

## Actual behavior
The bunded `index.html` gets renamed to `<parent-folder-name>.[hash].html`.

## To reproduce
Check out [this repo](https://github.com/s-weigand/dev-emoji-page) and run :
```console
npm run parcel:prod
```

**Comment by 101arrowz** [comment]
Fixed, thanks!
