### ISSUE TITLE
[BUG] "screenshots" doesn't specify its size in the manifest  

### ISSUE THREAD

**Issue by akkaranant** [101arrowz/pwa-manifest#36]
## Describe the bug
"screenshots" doesn't specify its sizes in the manifest 

## Actual behavior
no "sizes" added, like it did with "icons"

## Additional context
I love this plugin. It's almost perfect. "include"  worked great with "shortcuts" and else, except "screenshots" which is an automatic task. I'd be great if "screenshots" can be manual task by adding "screenshots" into "include".

**Comment by 101arrowz** [comment]
Screenshots now have their size specified automatically or manually. Thanks!
