### ISSUE TITLE
'pwamanifest.conifg.js' typo in source?

### ISSUE THREAD

**Issue by dannya** [101arrowz/pwa-manifest#37]
On line:
https://github.com/101arrowz/pwa-manifest/blob/538565f2e75cb17fba962d3c7e151bb509fd1c76/packages/parcel-transformer-pwa-manifest/index.ts#L29

should this be:

```'pwamanifest.config.js'``` ?

**Comment by 101arrowz** [comment]
Fixed, thanks for the report.
