### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: TypeError: Function has non-object prototype 'null' in instanceof check

### ISSUE THREAD

**Issue by MeiKatz** [101arrowz/pwa-manifest#44]
## Describe the bug
I tried to use `webpack-plugin-pwa-manifest` (without `html-webpack-plugin` if this matters) and I get the following error:
```
(node:204859) UnhandledPromiseRejectionWarning: TypeError: Function has non-object prototype 'null' in instanceof check
    at Function.[Symbol.hasInstance] (<anonymous>)
    at l.<anonymous> (***/node_modules/webpack-plugin-pwa-manifest/lib/index.js:2:2207)
    at l.emit (events.js:400:28)
    at l.emit (***/node_modules/@pwa-manifest/core/lib/index.js:2:12821)
    at l.<anonymous> (***/node_modules/@pwa-manifest/core/lib/index.js:2:13269)
    at Generator.next (<anonymous>)
    at ***/node_modules/@pwa-manifest/core/lib/index.js:2:319
    at new Promise (<anonymous>)
    at e (***/node_modules/@pwa-manifest/core/lib/index.js:2:67)
    at l.generate (***/node_modules/@pwa-manifest/core/lib/index.js:2:13152)
```

## Expected behavior
It should create the manifest file and the icons.

## Actual behavior
It doesn't.

## To reproduce
```js
new WebpackPluginPWAManifest({
  'name': process.env.APP_NAME,
  'shortName': process.env.APP_NAME,
  'startURL': '?pwa',
  'theme': '#00305e',
  'generateIconOptions': {
    'baseIcon': './public/base-icon.svg',
    'genFavicons': true
  }
}),
```

NodeJS-Version: v14.17.6
G++-Version: 11.2.1 20210728 (Red Hat 11.2.1-1)
Linux-Version: Linux fedora 5.13.16-200.fc34.x86_64
Webpack-Version: 5.49.0

The error appears in this [line 86 in the index.ts](https://github.com/101arrowz/pwa-manifest/blob/f31059c596f7b55df8ab70aa15a5b3af67f103fb/packages/webpack-plugin-pwa-manifest/index.ts#L86) because `SyncHook`'s `prototype` is `undefined`. Therefore the `instanceof` check fails.

**Comment by 101arrowz** [comment]
I haven't tested on Webpack 5 but I'm guessing they changed their plugin system. I'll update this when I can.

**Comment by AoDev** [comment]
@101arrowz Wanted to ask if you had the time to work on a Webpack 5 version.

**Comment by 101arrowz** [comment]
I haven't used Webpack in a long time since Parcel 2 has, in my experience, been able to completely replace it. So for the foreseeable future I'm not going to work on this but I'll look into it again if there's demand.
