### ISSUE TITLE
Something went wrong installing the "sharp" module (Mac M1)

### ISSUE THREAD

**Issue by HHogg** [101arrowz/pwa-manifest#53]
## Describe the bug

When trying to build, returning an error indicating there was a problem with "Sharp".

```
🚨 Build failed.

Error:
Something went wrong installing the "sharp" module

Could not resolve module "REDACTED/node_modules/sharp/build/Release/sharp.node" from "REDACTED/node_modules/sharp/lib/constructor.js"

- Remove the "node_modules/sharp" directory then run
"npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues


  Error:
  Something went wrong installing the "sharp" module
```

Investigating this, I could see that there was an error during a yarn install.

```
# This file contains the result of Yarn building a package (sharp@npm:0.25.4)
# Script name: install

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-arm64v8.tar.gz
ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
```

This appears to be when installing [pwa-manifest](https://github.com/101arrowz/pwa-manifest) it is using the Sharp version `0.25.4` where the ARM64 bindings are only provided from `0.29.0` onwards. 

Adding a resolution in my package.json did fix the issue like...

```json
  "resolutions": {
    "sharp": "0.30.2"
  }
```

I tried forking this repo and sending up a PR to bump the version, however yarn commands fail because the first thing it tries to do is get sharp 😄 (I only spent about 5 minutes on this so there might be a way around it).

**Comment by nsadeh** [comment]
I have also encountered this problem

**Comment by 101arrowz** [comment]
Should be fixed in the latest releases.

**Comment by HHogg** [comment]
Thanks @101arrowz
