### ISSUE TITLE
[FEATURE REQUEST] Maskable Icons

### ISSUE THREAD

**Issue by deckchairlabs** [101arrowz/pwa-manifest#7]
## The problem
It would be great to be able to pass custom properties to the generated icons within the manifest, I'm currently using the Parcel plugin, and would like to add `"purpose": "maskable any"` to the icons in the generated manifest.

<https://www.w3.org/TR/appmanifest/#dfn-badge-maskable>

**Comment by 101arrowz** [comment]
Added in 9cb1b0c895c43ea13538807704001edff362f27b. You should provide `"purpose": ["maskable", "any"]`, in the icon generation options, i.e. an array instead of space separation. Let me know if you encounter any bugs. Thanks for the feature request!

**Comment by deckchairlabs** [comment]
Awesome, thanks for the quick turnaround!
